### ISSUE TITLE
Trying to run on 10.2 version of Airflow and getting following error

### ISSUE THREAD

**Issue by sshanny** [ms32035/airflow-dag-dependencies#1]
____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/

[2019-09-03 00:41:48,325] {security.py:437} INFO - Start syncing user roles.
[2019-09-03 00:41:48,770] {security.py:195} INFO - Existing permissions for the role:Viewer within the database will persist.
[2019-09-03 00:41:49,268] {security.py:195} INFO - Existing permissions for the role:User within the database will persist.
[2019-09-03 00:41:49,656] {security.py:195} INFO - Existing permissions for the role:Op within the database will persist.
[2019-09-03 00:41:49,657] {security.py:346} INFO - Fetching a set of all permission, view_menu from FAB meta-table
[2019-09-03 00:41:51,979] {security.py:299} INFO - Cleaning faulty perms
[2019-09-03 00:41:53,462] {settings.py:174} INFO - settings.configure_orm(): Using pool settings. pool_size=5, pool_recycle=1800, pid=27
[2019-09-03 00:41:55,240] {plugins_manager.py:149} ERROR - getint() got an unexpected keyword argument 'fallback'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/airflow/plugins_manager.py", line 143, in <module>
    m = imp.load_source(namespace, filepath)
  File "/usr/local/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/plugins/dag-dependencies-plugin/dag_dependencies_plugin.py", line 12, in <module>
    class DAGDependenciesView(BaseView):
  File "/usr/local/airflow/plugins/dag-dependencies-plugin/dag_dependencies_plugin.py", line 18, in DAGDependenciesView
    "dag_dependencies_plugin", "refresh_interval", fallback=300
TypeError: getint() got an unexpected keyword argument 'fallback'
[2019-09-03 00:41:55,250] {plugins_manager.py:150} ERROR - Failed to import plugin /usr/local/airflow/plugins/dag-dependencies-plugin/dag_dependencies_plugin.py

**Comment by ms32035** [comment]
Quite possible, maybe fallback was added later. This plugin was built off master. Just edit your local file and set the refresh interval directly to what you want it to be in seconds

**Comment by sshanny** [comment]
Marcin,

Thanks for the quick reply.  The menu item now appears but I am getting a 404 error when I click on it.  Will this happen if we actually don’t have any dependencies?

Airflow 404 = lots of circles

ed4cf51bb55d

—Sean

**Comment by ms32035** [comment]
No, looks like some other issue, but can't guess without logs

**Comment by sshanny** [comment]
Marcin,

Sorry should have included the entry although not sure what help it will be.  This is from the web server. Don’t see anything in scheduler or worker logs.

[2019-09-03 01:14:08 +0000] [34] [INFO] Worker exiting (pid: 34)
172.19.0.1 - - [03/Sep/2019:01:14:12 +0000] "GET /dag-dependencies HTTP/1.1" 404 3697 "http://localhost:8080/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"

**Comment by ms32035** [comment]
Are you using RBAC UI?

**Comment by sshanny** [comment]
Yes.

**Comment by ms32035** [comment]
The plugin is loaded on webserver start. Anything there?

**Comment by sshanny** [comment]
Marcin,

Nothing at startup in the logs at all concerning the plugin.  I hit configuration menu item immediately after try dag-dependencies and there is the output.  Is there some logging I can add to plugin to see what is happening?

—Sean


[2019-09-03 13:52:24 +0000] [114] [INFO] Worker exiting (pid: 114)
172.19.0.1 - - [03/Sep/2019:13:52:27 +0000] "GET /dag-dependencies HTTP/1.1" 404 3697 "http://localhost:8080/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
172.19.0.1 - - [03/Sep/2019:13:52:43 +0000] "GET /configuration HTTP/1.1" 200 115923 "http://localhost:8080/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"

**Comment by ms32035** [comment]
My best guess is that 1.10.2 does not correctly support all plugin features in RBAC. https://github.com/apache/airflow/pull/4036
https://github.com/apache/airflow/pull/4598
